
CREATE TABLE EMPLOYEES (
    emp_id integer PRIMARY KEY,
    emp_name  varchar(50),
    salary integer
);

INSERT INTO EMPLOYEES VALUES (101, 'Amulya', 30000);
INSERT INTO EMPLOYEES VALUES (102, 'Rahul', 35000);
INSERT INTO EMPLOYEES VALUES (103, 'Sneha', 40000);
COMMIT;





